employee/urls.py
from django.urls import path
from employee import views

urlpatterns=[
    path('add',views.EmployeeCreateView.as_view(),name="emp-create"),
    path("all",views.EmployeeListView.as_view(),name="emp-list"),
    path("details/<str:emp_id>",views.EmployeeDetailView.as_view(),name="emp-detail"),
    path("change/<str:e_id>",views.EmployeeEditView.as_view(),name="emp-edit"),
    path("remove/<str:e_id>",views.remove_employee,name="emp-remove"),
    path("",views.index,name="index"),
    path("accounts/signup",views.SignUpView.as_view(),name="sign-up"),
    path("accounts/signin",views.LoginView.as_view(),name="sign-in"),
    path("accounts/signout",views.sign_out,name="signout")

]

employeemanagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/',include("employee.urls")),
    path('calculator/',include("calculator.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    eid=models.CharField(max_length=120,primary_key=True)
    profile_pic=models.ImageField(upload_to="profilepics",null=True)
    employee_name=models.CharField(max_length=120)
    designation=models.CharField(max_length=120)
    salary=models.PositiveIntegerField()
    email=models.EmailField(unique=True)
    experience=models.PositiveIntegerField(null=0)

    def __str__(self):
        return self.employee_name

employee/forms.py
from django import forms
from employee.models import Employee
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class EmployeeCreateForm(forms.ModelForm):
    class Meta:
        model=Employee
        fields="__all__"

        widgets={
            "eid":forms.TextInput(attrs={"class":"form-control"}),
            "employee_name":forms.TextInput(attrs={"class":"form-control"}),
            "designation":forms.TextInput(attrs={"class":"form-control"}),
            "salary":forms.NumberInput(attrs={"class":"form-control"}),
            "email":forms.EmailInput(attrs={"class":"form-control"}),
            "experience":forms.NumberInput(attrs={"class":"form-control"})
        }

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=["first_name",
                "last_name",
                "email",
                "username",
                "password1",
                "password2"]

class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput())

employee/views.py
from django.shortcuts import render
from employee.forms import EmployeeCreateForm
from django.views.generic import View
from employee.models import Employee
from django.contrib import messages
from django.shortcuts import redirect
from employee.forms import UserRegistrationForm
from employee.forms import LoginForm
from django.contrib.auth import authenticate,login,logout
from django.utils .decorators import method_decorator

def signin_required(fn):
    def wrapper(request,*args,**kwargs):
        if request.user.is_authenticated:
            return fn(request,*args,**kwargs)
        else:
            return redirect("sign-in")
    return wrapper

@method_decorator(signin_required,name="dispatch")
class EmployeeCreateView(View):
    def get(self,request,*args,**kwargs):
        form=EmployeeCreateForm()
        return render(request,"emp-add.html",{"form":form})
    def post(self,request,*args,**kwargs):
        form=EmployeeCreateForm(request.POST,files=request.FILES)
        if form.is_valid():
            form.save()

            messages.success(request,"employee has been added")
            return render(request,"emp-add.html", {"form": form})
        else:
            messages.error(request,"employee added failed")
            return render(request,"emp-add.html", {"form": form})

@method_decorator(signin_required,name="dispatch")
class EmployeeListView(View):
    def get(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            qs=Employee.objects.all()
            return render(request,"emp-list.html",{"employees":qs})
        else:
            return redirect("sign-in")

@method_decorator(signin_required,name="dispatch")
class EmployeeDetailView(View):
    def get(self,request,*args,**kwargs):
        qs=Employee.objects.get(eid=kwargs.get("emp_id"))
        return render(request,"emp-detail.html",{"employee":qs})


class EmployeeEditView(View):
    def get(self,request,*args,**kwargs):
        eid=kwargs.get("e_id")
        employee=Employee.objects.get(eid=eid)
        form=EmployeeCreateForm(instance=employee)
        return render(request,"emp-edit.html",{"form":form})
    def post(self,request,*args,**kwargs):
        eid = kwargs.get("e_id")
        employee = Employee.objects.get(eid=eid)
        form = EmployeeCreateForm(request.POST,instance=employee,files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "employee has been updated")
            return render(request, "emp-list.html", {"form": form})
        else:
            messages.error(request, "employee added failed")
            return render(request, "emp-add.html", {"form": form})


def remove_employee(request,*args,**kwargs):
    eid=kwargs.get("e_id")
    employee=Employee.objects.get(eid=eid)
    employee.delete()
    messages.error(request,"employee has been removed")
    return redirect("emp-list")

@method_decorator
def index(request):
    return render(request,"base.html")

class SignUpView(View):
    def get(self,request,*args,**kwargs):
        form=UserRegistrationForm()
        return render(request,"registration.html",{"form":form})
    def post(self,request,*args,**kwargs):
        form=UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Your account has been created")
            return redirect("sign-in")
        else:
            messages.error(request, "account creation has been failed")
            return render(request,"registration.html",{"form":form})


class LoginView(View):
    def get(self,request,*args,**kwargs):
        form=LoginForm
        return render(request,"log_in.html",{"form":form})
    def post(self,request,*args,**kwargs):
        form=LoginForm(request.POST)
        if form.is_valid():
            uname=form.cleaned_data.get("username")
            pw=form.cleaned_data.get("password")
            user=authenticate(request,username=uname,password=pw)
            if user:
                login(request,user)
                print("success")
                return redirect("emp-list")
            else:
                messages.error(request,"invalid credentials")
                return render(request, "log_in.html", {"form": form})

def sign_out(request,*args,**kwargs):
    logout(request)
    return redirect("sign-in")

employee/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add</title>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}

                <div class="mb-3">
                    <input type="submit">
                </div>
            </form>
        </div>
        <div class="col-4">
            {%if res%}
            <span>Result=</span>{{res}}
            {%endif%}
        </div>
    </div>
</div>
</body>
</html>

employee/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Simple Sidebar - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">Employee Details</div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Profiles</a>

                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <button class="btn btn-primary" id="sidebarToggle">Toggle Menu</button>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
<!--                                <li class="nav-item active"><a class="nav-link" href="#!">Home</a></li>-->
<!--                                <li class="nav-item"><a class="nav-link" href="#!">Link</a></li>-->
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{request.user}}</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="#!">Action</a>
                                        <a class="dropdown-item" href="#!">Another action</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{%url 'signout'%}">logout</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">
                    {%block body_block%}
                    {%endblock%}
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
    </body>
</html>

employee/templates/emp-add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>employee</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4">
            <input class="mt-3" type="file" name="profile_pic" id="id_profile_pic">
            <input class="mt-3" type="text" name="eid" id="id_eid" placeholder="enter employee id">
            <input class="mt-3" type="text" name="employee_name" id="id_employee_name" placeholder="enter employee name">
            <input class="mt-3" type="text" name="designation" id="id_designation" placeholder="enter designation">
            <input class="mt-3" type="text" name="salary" id="id_salary" placeholder="enter salary">
            <input class="mt-3" type="text" name="email" id="id_email" placeholder="enter email">

            <input class="mt-3" type="text" name="experience" id="id_experience" placeholder="enter experience">

            <input class="mt-3" type="submit">


        </div>
        <div class="col-4">

        </div>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
<!--                <input type="submit">-->
            </div>
            <div class="col-4"></div>
        </div>
    </div>


</form>

</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</html>

employee/templates/emp-detail.html
{%extends 'base.html'%}
{%block body_block%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">

            <div class="card" style="width: 18rem;">
  <img src="{{employee.profile_pic.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><strong>NAME : </strong>{{employee.employee_name}}</h5>
    <p class="card-text"><strong>EMPLOYEE ID : </strong>{{employee.eid}}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><STRONG>DESIGNATION : </STRONG>{{employee.designation}}</li>
    <li class="list-group-item"><STRONG>SALARY : </STRONG>{{employee.salary}}</li>
    <li class="list-group-item"><STRONG>EMAIL : </STRONG>{{employee.email}}</li>
    <li class="list-group-item"><STRONG>EXPERIENCE : </STRONG>{{employee.experience}}</li>

  </ul>
<!--  <div class="card-body">-->
<!--    <a href="#" class="card-link">{{employee.experience}}</a>-->
<!--    <a href="#" class="card-link">{{employee.eid}}</a>-->
<!--  </div>-->
</div>

        </div>
        <div class="col-4"></div>
    </div>
</div>

</body>
</html>
{%endblock%}

employee/templates/emp-edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>employee</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%if messages%}
                {%for message in messages%}
                    {{message}}
                {%endfor%}
            {%endif%}
        </div>
        <div class="col-4"></div>
    </div>
    <div class="row mt-5">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form.as_p}}
                <input type="submit">
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>



</body>
</html>

employee/templates/emp-list.html
{% extends 'base.html'%}
{%block body_block%}

<div class="container">
     <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%if messages%}
                {%for message in messages%}
                    {{message}}
                {%endfor%}
            {%endif%}
        </div>
        <div class="col-4"></div>
    </div>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <table class="table">
                <tr>
                    <th>Employee ID</th>
                    <th>Employee name</th>
                    <th>Email</th>
                    <th>Action</th>
                </tr>
                {%for emp in employees%}
                <tr>
                    <td>{{emp.eid}}</td>
                    <td>{{emp.employee_name}}</td>
                    <td>{{emp.email}}</td>
                    <td>
                        <a href="{%url 'emp-detail' emp.eid%}">view</a>
                        <a href="{%url 'emp-edit' emp.eid%}">edit</a>
                        <a href="{%url 'emp-remove' emp.eid%}">delete</a>


                    </td>
                </tr>
                {%endfor%}
            </table>
        </div>
        <div class="col-2"></div>
    </div>
</div>

{%endblock%}

employee/templates/log_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title><script src="https://kit.fontawesome.com/462b907c66.js" crossorigin="anonymous"></script>
</head>
<body>
   <!-- fa-5x (icon te size increase chettan 1-10 vare kodukaam) -->
    <i class="fa-solid fa-right-to-bracket fa-5x"></i>
    <h1>login form</h1>
   <hr>

<!--   <form action="">-->
<!--       <label for="username"></label>-->
<!--       <input type="text" id="al" placeholder="username">-->
<!--       <label for="pl">password</label>-->
<!--       <input type="password" id="pl"><br>-->
<!--       <hr>-->
<!--       <button>login</button>-->
<!--<div>-->
    <form action="" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit">
    </form>
</div>
       <!-- hr horizontal aayi line kodukkan -->
       <!-- place holder paranja pettite ullil name kodukkan -->
   </form>
</body>
</html>

employee/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>registration</title>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-4"></div>
    <div class="col-4">
            {%if messages%}
                {%for message in messages%}
                    {{message}}
                {%endfor%}
            {%endif%}
    </div>
    <div class="col-4"></div>
  </div>
  <div class="col-2"></div>
  <div class="col-8">
    <form action="" method="post">
      {%csrf_token%}
      {{form.as_p}}
      <input type="submit">
    </form>
  </div>
  <div class="col-2"></div>
</div>
</body>
</html>

employee/templates/wordcount.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>wordcount</title>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post">
                {%csrf_token%}
                <div class="mb-3">
                    <input type="text" name="word" placeholder="enter text here" class="form-control">
                </div>
                <div class="mb-3">
                    <input type="submit">
                </div>
            </form>
        </div>
        <div class="col-4">
        </div>
    </div>
</div>
</body>
</html>